blog/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as'=>'frontHome.index', 'uses'=>'FrontHomeController@index']);

Auth::routes();



Route::get('producer/showall',array('as'=>'producer.showall','uses'=>'ProducerController@showall'));

Route::get('producer/{id}',array('as'=>'producer.showa','uses'=>'ProducerController@showa'));

/*
|
| Back-End
|
*/
Route::group(['middleware'=>'auth'], function(){
	Route::resource('frontHome', 'FrontHomeController');

	Route::resource('objective', 'ProjectObjectiveController');

	Route::resource('information', 'ProjectInformationController');

	Route::resource('productinformation', 'ProductInformationController');

	Route::resource('productvalue', 'ProductValueController');

	Route::resource('contactus', 'ContactUsController');

	Route::resource('payment', 'PaymentController');

	Route::resource('logistic', 'LogisticController');

	Route::get('basket/edit_acc', ['as'=>'basket.edit_acc', 'uses'=>'BasketController@edit_acc']);
	Route::patch('basket/update_acc/{id}', ['as'=>'basket.update_acc', 'uses'=>'BasketController@update_acc']); //



	// Route::get('producer/createa',array('as'=>'producer.createa','uses'=>'ProducerController@createa'));

	Route::resource('producer', 'ProducerController');



	Route::get('reports/google',array('as'=>'reports.google','uses'=>'ReportsController@google'));
	Route::get('reports/bestsaler',array('as'=>'reports.bestsaler','uses'=>'ReportsController@bestsaler'));
	Route::resource('reports', 'ReportsController');
});


// Route::get('/home', 'HomeController@index')->name('home');

Route::get('home/checkout_buy',array('as'=>'home.checkout_buy','uses'=>'HomeController@checkout_buy'));

Route::get('home/seemore_products/{id}',array('as'=>'home.seemore_products','uses'=>'HomeController@seemore_products')); //update_status_basket

Route::get('home/update_status_basket/{id}',array('as'=>'home.update_status_basket','uses'=>'HomeController@update_status_basket')); //history

Route::get('home/update_cart_products/{id}',array('as'=>'home.update_cart_products','uses'=>'HomeController@update_cart_products'));

Route::get('/history',array('as'=>'home.history','uses'=>'HomeController@history'));

Route::get('/home', array('as'=>'home.index','uses'=>'HomeController@index'));


Route::get('deleteimg/{id}', ['as'=>'users.deleteimg', 'uses'=>'UserController@deleteimg']); 
Route::resource('users', 'UserController');

Route::resource('produceTypes', 'ProduceTypeController');

Route::resource('produces', 'ProduceController');

// Route::resource('provinces', 'ProvinceController');

// Route::resource('districts', 'DistrictController');

// Route::resource('subDistricts', 'SubDistrictController');

// Route::resource('zipcodes', 'ZipcodeController');



Route::get('customer/district/{id}',array('as'=>'create.ajax','uses'=>'AppBaseController@getDistrict'));

Route::get('customer/subdistrict/{id}',array('as'=>'create.ajax','uses'=>'AppBaseController@getSubDistrict'));

Route::get('customer/testFacebook','CustomerController@testFacebook');

Route::post('customer/testPost',array('as'=>'testPost','uses'=>'CustomerController@testPost'));

Route::get('customer/facebook',array('as'=>'customer/facebook', 'uses'=>'CustomerController@redirectToProvider'));
Route::get('customer/facebook/callback',array('as'=>'customer/facebook/callback ','uses'=>'CustomerController@handleProviderCallback'));

Route::get('customer/google',array('as'=>'customer/google', 'uses'=>'CustomerController@redirectToProviderGoogle'));
Route::get('customer/google/callback',array('as'=>'customer/google/callback','uses'=>'CustomerController@handleProviderCallbackGoogle'));

Route::post('customer/addRegister',array('as'=>'customer/addRegister','uses'=>'CustomerController@addRegister'));

Route::post('customer/addLitleRegister',array('as'=>'customer.addLitleRegister','uses'=>'CustomerController@addLitleRegister'));

//Route::resource('producer', 'ProducerController');
Route::resource('customers', 'CustomerController');

/*
|
| Front-End
|
*/
// Route::get('/', function () {
//     // return view('welcome');
//     return view('front.home');
// });



// Route::get('/', function () {
// 		return 'It work!';
// 	});



Route::get('objective', ['as'=>'objective.index', 'uses'=>'ProjectObjectiveController@index']);

Route::get('information', ['as'=>'information.index', 'uses'=>'ProjectInformationController@index']);

Route::get('productinformation', ['as'=>'productinformation.index', 'uses'=>'ProductInformationController@index']);

Route::get('productvalue', ['as'=>'productvalue.index', 'uses'=>'ProductValueController@index']);

Route::get('contactus', ['as'=>'contactus.index', 'uses'=>'ContactUsController@index']);

Route::get('payment', ['as'=>'payment.index', 'uses'=>'PaymentController@index']);

Route::get('logistic', ['as'=>'logistic.index', 'uses'=>'LogisticController@index']);

// Route::get('customer/register', 'CustomerController@register');
Route::get('customer/register', ['as'=>'customer.register', 'uses'=>'CustomerController@register']);

// Route::get('customers/{id}/edit', ['as'=>'customers.edit', 'uses'=>'CustomerController@edit']);

Route::get('member/forgotpassword', ['as'=>'member.forgotpassword', 'uses'=>'MemberController@forgotpassword']);
Route::post('member/sentemailforgotpassword', ['as'=>'member.sentemailforgotpassword', 'uses'=>'MemberController@sentemailforgotpassword']);
Route::resource('member', 'MemberController');

//add a route to that method separately, before you register the resource:
//For Basket
Route::get('basket/getBasket', ['as'=>'basket.getBasket', 'uses'=>'BasketController@getBasket']);
Route::get('basket/getexistbasket', ['as'=>'basket.getexistbasket', 'uses'=>'BasketController@getexistbasket']);
Route::get('basket/addBasket', ['as'=>'basket.addBasket', 'uses'=>'BasketController@addBasket']);
Route::get('basket/updateBasket', ['as'=>'basket.updateBasket', 'uses'=>'BasketController@updateBasket']);
Route::get('basket/addBasketByAdmin', ['as'=>'basket.addBasketByAdmin', 'uses'=>'BasketController@addBasketByAdmin']);
Route::get('basket/updateBasketQtyForCartPage', ['as'=>'basket.updateBasketQtyForCartPage', 'uses'=>'BasketController@updateBasketQtyForCartPage']);
Route::get('basket/updateBasketQtyForCartPageByAdmin', ['as'=>'basket.updateBasketQtyForCartPageByAdmin', 'uses'=>'BasketController@updateBasketQtyForCartPageByAdmin']);

Route::get('baskettype/{id}', ['as'=>'baskettype.showbaseontype', 'uses'=>'BasketController@showbaseontype']); 

Route::get('basket/removeProductFromBasket', ['as'=>'basket.removeProductFromBasket', 'uses'=>'BasketController@removeProductFromBasket']);
Route::get('basket/removeProductFromBasketByAdmin', ['as'=>'basket.removeProductFromBasketByAdmin', 'uses'=>'BasketController@removeProductFromBasketByAdmin']);

Route::get('basket/editCustomer', ['as'=>'basket.editCustomer', 'uses'=>'BasketController@editCustomer']);
Route::patch('basket/updateCustomer', ['as'=>'basket.updateCustomer', 'uses'=>'BasketController@updateCustomer']);
Route::patch('basket/updateCustomerMap', ['as'=>'basket.updateCustomerMap', 'uses'=>'BasketController@updateCustomerMap']);

//For card and checkout
Route::get('cart/{basketkey}', ['as'=>'basket.cart', 'uses'=>'BasketController@cart']);

Route::get('basket/checkout', ['as'=>'basket.checkout', 'uses'=>'BasketController@checkout']);

Route::get('basket/get_data_googlemap_api', ['as'=>'basket.get_data_googlemap_api', 'uses'=>'BasketController@get_data_googlemap_api']); 
Route::get('basket/googlemap_api', ['as'=>'basket.googlemap_api', 'uses'=>'BasketController@googlemap_api']); 


Route::get('basket/checkou', ['as'=>'basket.checkou', 'uses'=>'BasketController@checkou']); 

Route::post('basket/checkout_uploadfile', ['as'=>'basket.checkout_uploadfile', 'uses'=>'BasketController@checkout_uploadfile']); //

Route::post('basket/checkout_uploadfile_again', ['as'=>'basket.checkout_uploadfile_again', 'uses'=>'BasketController@checkout_uploadfile_again']);

Route::get('basket/checkout_getfile', ['as'=>'basket.checkout_getfile', 'uses'=>'BasketController@checkout_getfile']); 


Route::post('basket/checkout_buy', ['as'=>'basket.checkout_buy', 'uses'=>'BasketController@checkout_buy']); //status_checkout_buy
Route::get('basket/checkout_buyByAdmin',array('as'=>'basket.checkout_buyByAdmin','uses'=>'BasketController@checkout_buyByAdmin'));

Route::get('basket/status_checkout_buy', ['as'=>'basket.status_checkout_buy', 'uses'=>'BasketController@status_checkout_buy']); //seemore_products

Route::get('seemore_products/{id}', ['as'=>'basket.seemore_products', 'uses'=>'BasketController@seemore_products']); 

Route::resource('basket', 'BasketController');




Route::get('gmenu_logoutin_d', ['as'=>'getview.gmenu_logoutin_d', 'uses'=>'GetviewController@gmenu_logoutin_d']);
Route::get('gmenu_logoutin_m', ['as'=>'getview.gmenu_logoutin_m', 'uses'=>'GetviewController@gmenu_logoutin_m']); 

Route::get('gmenu_historybuy_d', ['as'=>'getview.gmenu_historybuy_d', 'uses'=>'GetviewController@gmenu_historybuy_d']);
Route::get('gmenu_historybuy_m', ['as'=>'getview.gmenu_historybuy_m', 'uses'=>'GetviewController@gmenu_historybuy_m']);

// Route::get('gfooter_line1_d', ['as'=>'getview.gfooter_line1_d', 'uses'=>'GetviewController@gfooter_line1_d']);
// Route::get('gfooter_line1_m', ['as'=>'getview.gfooter_line1_m', 'uses'=>'GetviewController@gfooter_line1_m']);
Route::resource('getview', 'GetviewController');


// Route::get('member/login', ['as'=>'member.login', 'uses'=>'MemberController@index']); //Request $request
// Route::post('member/store', ['as'=>'member.store', 'uses'=>'MemberController@store']);

blog/resources/views/layouts/_front.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>ตลาดนัดสีเขียวกินสบายใจ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Font-awesome-->
    <link href="{{asset('font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" >
    <!-- Custom CSS -->
    <link href="{{asset('css/custom.front.css')}}" rel="stylesheet">
    <!-- Select2 -->
    {!! Html::style('adminlte/plugins/select2/select2.min.css') !!}
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-green">
      <a class="navbar-brand" href="#">ตลาดนัดสีเขียว กินสบายใจ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item {{((Request::is('/')) ? 'active':'')}}">
            <a class="nav-link" href="{{ url('/') }}"><i class="fa fa-home" aria-hidden="true"></i> หน้าหลัก</a>
          </li>
          <li class="nav-item {{((Request::is('objective')) ? 'active':'')}}">
            <a class="nav-link" href="{{route('objective.index')}}"><i class="fa fa-globe" aria-hidden="true"></i> แนวคิดโครงการ</a>
          </li>
          <li class="nav-item {{((Request::is('information')) ? 'active':'')}}">
            <a class="nav-link" href="{{route('information.index')}}"><i class="fa fa-database" aria-hidden="true"></i> ข้อมูลโครงการ</a>
          </li>
          <li class="nav-item {{((Request::is('productinformation')) ? 'active':'')}}">
            <a class="nav-link" href="{{route('productinformation.index')}}"><i class="fa fa-pagelines" aria-hidden="true"></i> ข้อมูลผลิตภัณฑ์</a>
          </li>
          <li class="nav-item {{((Request::is('productvalue')) ? 'active':'')}}">
            <a class="nav-link" href="{{route('productvalue.index')}}"><i class="fa fa-bar-chart" aria-hidden="true"></i> คุณค่าของสินค้า</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fa fa-leaf" aria-hidden="true"></i> กลุ่มผลิตอินทรีย์</a>
          </li>
          <li class="nav-item dropdown {{((Request::is('payment')) ||  Request::is('logistic') ? 'active':'')}}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-barcode" aria-hidden="true"></i> การซื้อสินค้า
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{route('basket.index')}}"><i class="fa fa-shopping-basket" aria-hidden="true"></i> ตะกร้าสินค้า</a>
              <a class="dropdown-item" href="{{route('payment.index')}}"><i class="fa fa-btc" aria-hidden="true"></i> การชำระเงิน</a>
              <a class="dropdown-item" href="{{route('logistic.index')}}"><i class="fa fa-plane" aria-hidden="true"></i> การจัดส่งสินค้า</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{route('customer.register')}}"><i class="fa fa-pencil" aria-hidden="true"></i> สมัครสมาชิก</a>
            </div>
          </li>
          <li class="nav-item {{((Request::is('contactus')) ? 'active':'')}}">
            <a class="nav-link" href="{{route('contactus.index')}}"><i class="fa fa-envelope" aria-hidden="true"></i> ติดต่อเรา</a>
          </li>
        </ul>
      </div>
    </nav>

   {{--  <div class="container"> --}}
      @yield('content')
    {{-- </div> --}}


    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <!-- jQuery 3.1.1 -->
    {!! Html::script('adminlte/plugins/jQuery/jquery-3.1.1.min.js') !!}
    <script src="{{asset('vendor/bootstrap/popper.min.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!-- Select2 -->
    {!! Html::script('adminlte/plugins/select2/select2.full.min.js') !!}
    @include('layouts.script')
    @yield('scripts')
  </body>
</html>

blog/resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

blog/resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

blog/resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ตลาดนัดสีเขียวกินสบายใจ</title>

    <!-- Bootstrap 3.3.6 -->
    {!! Html::style('adminlte/bootstrap/css/bootstrap.min.css') !!}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- Date Picker -->
    {!! Html::style('adminlte/plugins/datepicker/datepicker3.css') !!}

    <!-- Select2 -->
    {!! Html::style('adminlte/plugins/select2/select2.min.css') !!}

    @yield('css')
  </head>
  <body>
      <div class="wrapper">
          <!-- Main Header -->
          <header class="main-header">
              <!-- Header Navbar -->
              <nav class="navbar navbar-static-top" role="navigation">

              </nav>
          </header>
          <div class="content-wrapper">
              @yield('content')
          </div>
      </div>
    <!-- jQuery 3.1.1 -->
    {!! Html::script('adminlte/plugins/jQuery/jquery-3.1.1.min.js') !!}

    <!-- Bootstrap 3.3.6 -->
    {!! Html::script('adminlte/bootstrap/js/bootstrap.min.js') !!}

    <!-- datepicker -->
    {!! Html::script('adminlte/plugins/datepicker/bootstrap-datepicker.js') !!}

    <!-- Select2 -->
    {!! Html::script('adminlte/plugins/select2/select2.full.min.js') !!}

    @include('layouts.script')
    @yield('scripts')
  </body>
</html>

blog/resources/views/layouts/menu.blade.php
<li class="{{ Request::is('home') ? 'active' : '' }}">
    <a href="{!! route('home.index') !!}"><i class="fa fa-edit"></i><span>คำสั่งซื้อ</span></a>
</li>

<li class="{{ Request::is('history') ? 'active' : '' }}">
    <a href="{!! route('home.history') !!}"><i class="fa fa-edit"></i><span>ประวัติคำสั่งซื้อ</span></a>
</li>

<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{!! route('users.index') !!}"><i class="fa fa-edit"></i><span>ผู้ดูแลระบบ</span></a>
</li>

<li class="{{ Request::is('produceTypes*') ? 'active' : '' }}">
    <a href="{!! route('produceTypes.index') !!}"><i class="fa fa-edit"></i><span>ประเภทตะกร้าสินค้า</span></a>
</li>

<li class="{{ Request::is('produces*') ? 'active' : '' }}">
    <a href="{!! route('produces.index') !!}"><i class="fa fa-edit"></i><span>สินค้า</span></a>
</li>

<li class="{{ Request::is('customers*') ? 'active' : '' }}">
    <a href="{!! route('customers.index') !!}"><i class="fa fa-edit"></i><span>จัดการข้อมูลลูกค้า</span></a>
</li>



<li class="{{ Request::is('frontHome*') ? 'active' : '' }}">
    <a href="{!! route('frontHome.create') !!}"><i class="fa fa-edit"></i><span>จัดการหน้าแรก</span></a>
</li>

<li class="{{ Request::is('objective*') ? 'active' : '' }}">
    <a href="{!! route('objective.create') !!}"><i class="fa fa-edit"></i><span>จัดการแนวคิดโครงการ</span></a>
</li>

<li class="{{ Request::is('information*') ? 'active' : '' }}">
    <a href="{!! route('information.create') !!}"><i class="fa fa-edit"></i><span>จัดการข้อโครงการ</span></a>
</li>

<li class="{{ Request::is('producer*') ? 'active' : '' }}">
    <a href="{!! route('producer.index') !!}"><i class="fa fa-edit"></i><span>จัดการกลุ่มผลิตอินทรีย์</span></a>
</li>



<li class="{{ Request::is('productinformation*') ? 'active' : '' }}">
    <a href="{!! route('productinformation.create') !!}"><i class="fa fa-edit"></i><span>จัดการข้อมูลผลิตภัณฑ์</span></a>
</li>

<li class="{{ Request::is('productvalue*') ? 'active' : '' }}">
    <a href="{!! route('productvalue.create') !!}"><i class="fa fa-edit"></i><span>จัดการข้อมูลคุณค่าของสินค้า</span></a>
</li>

<li class="{{ Request::is('payment*') ? 'active' : '' }}">
    <a href="{!! route('payment.create') !!}"><i class="fa fa-edit"></i><span>จัดการข้อมูลการชำระเงิน</span></a>
</li>

<li class="{{ Request::is('logistic*') ? 'active' : '' }}">
    <a href="{!! route('logistic.create') !!}"><i class="fa fa-edit"></i><span>จัดการข้อมูลการจัดส่ง</span></a>
</li>

<li class="{{ Request::is('contactus*') ? 'active' : '' }}">
    <a href="{!! route('contactus.create') !!}"><i class="fa fa-edit"></i><span>จัดการข้อมูลติดต่อเรา</span></a>
</li>


<li class="{{ Request::is('basket*') ? 'active' : '' }}">
    <a href="{!! route('basket.edit_acc') !!}"><i class="fa fa-edit"></i><span>จัดการหน้าสั่งซื้อสินค้า</span></a>
</li>


<li class="{{ Request::is('reports.index') ? 'active' : '' }}">
    <a href="{!! route('reports.index') !!}"><i class="fa fa-edit"></i><span>รายงานสรุปสินค้า/ลูกค้า</span></a>
</li>

<li class="{{ Request::is('reports.google') ? 'active' : '' }}">
    <a href="{!! route('reports.google') !!}"><i class="fa fa-edit"></i><span>รายงานสถิติ (google analytics)</span></a>
</li>

blog/resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
            @if(count(Auth::user()->photo_file) > 0)
                {{ Html::image(Auth::user()->photo_file, 'a User Image', array('class' => 'img-circle')) }}
            @else
                {{ Html::image('imgUser/User.png', 'a User Image', array('class' => 'img-circle')) }}
            @endif    
                <!-- <img src="{{URL::asset('/').Auth::user()->photo_file}}" class="img-circle"
                     alt="User Image"/> -->
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
{{--         <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form> --}}
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

blog/resources/views/layouts/stype.blade.php
<style>
    tr.back-tr{
        background-color : #E6E6E6;
    }
</style>