blog/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as'=>'frontHome.index', 'uses'=>'FrontHomeController@index']);

Auth::routes();



Route::get('producer/showall',array('as'=>'producer.showall','uses'=>'ProducerController@showall'));

Route::get('producer/{id}',array('as'=>'producer.showa','uses'=>'ProducerController@showa'));

/*
|
| Back-End
|
*/
Route::group(['middleware'=>'auth'], function(){
	Route::resource('frontHome', 'FrontHomeController');

	Route::resource('objective', 'ProjectObjectiveController');

	Route::resource('information', 'ProjectInformationController');

	Route::resource('productinformation', 'ProductInformationController');

	Route::resource('productvalue', 'ProductValueController');

	Route::resource('contactus', 'ContactUsController');

	Route::resource('payment', 'PaymentController');

	Route::resource('logistic', 'LogisticController');

	Route::get('basket/edit_acc', ['as'=>'basket.edit_acc', 'uses'=>'BasketController@edit_acc']);
	Route::patch('basket/update_acc/{id}', ['as'=>'basket.update_acc', 'uses'=>'BasketController@update_acc']); //



	// Route::get('producer/createa',array('as'=>'producer.createa','uses'=>'ProducerController@createa'));

	Route::resource('producer', 'ProducerController');



	Route::get('reports/google',array('as'=>'reports.google','uses'=>'ReportsController@google'));
	Route::get('reports/bestsaler',array('as'=>'reports.bestsaler','uses'=>'ReportsController@bestsaler'));
	Route::resource('reports', 'ReportsController');
});


// Route::get('/home', 'HomeController@index')->name('home');

Route::get('home/checkout_buy',array('as'=>'home.checkout_buy','uses'=>'HomeController@checkout_buy'));

Route::get('home/seemore_products/{id}',array('as'=>'home.seemore_products','uses'=>'HomeController@seemore_products')); //update_status_basket

Route::get('home/update_status_basket/{id}',array('as'=>'home.update_status_basket','uses'=>'HomeController@update_status_basket')); //history

Route::get('home/update_cart_products/{id}',array('as'=>'home.update_cart_products','uses'=>'HomeController@update_cart_products'));

Route::get('/history',array('as'=>'home.history','uses'=>'HomeController@history'));

Route::get('/home', array('as'=>'home.index','uses'=>'HomeController@index'));


Route::get('deleteimg/{id}', ['as'=>'users.deleteimg', 'uses'=>'UserController@deleteimg']); 
Route::resource('users', 'UserController');

Route::resource('produceTypes', 'ProduceTypeController');

Route::resource('produces', 'ProduceController');

// Route::resource('provinces', 'ProvinceController');

// Route::resource('districts', 'DistrictController');

// Route::resource('subDistricts', 'SubDistrictController');

// Route::resource('zipcodes', 'ZipcodeController');



Route::get('customer/district/{id}',array('as'=>'create.ajax','uses'=>'AppBaseController@getDistrict'));

Route::get('customer/subdistrict/{id}',array('as'=>'create.ajax','uses'=>'AppBaseController@getSubDistrict'));

Route::get('customer/testFacebook','CustomerController@testFacebook');

Route::post('customer/testPost',array('as'=>'testPost','uses'=>'CustomerController@testPost'));

Route::get('customer/facebook',array('as'=>'customer/facebook', 'uses'=>'CustomerController@redirectToProvider'));
Route::get('customer/facebook/callback',array('as'=>'customer/facebook/callback ','uses'=>'CustomerController@handleProviderCallback'));

Route::get('customer/google',array('as'=>'customer/google', 'uses'=>'CustomerController@redirectToProviderGoogle'));
Route::get('customer/google/callback',array('as'=>'customer/google/callback','uses'=>'CustomerController@handleProviderCallbackGoogle'));

Route::post('customer/addRegister',array('as'=>'customer/addRegister','uses'=>'CustomerController@addRegister'));

Route::post('customer/addLitleRegister',array('as'=>'customer.addLitleRegister','uses'=>'CustomerController@addLitleRegister'));

//Route::resource('producer', 'ProducerController');
Route::resource('customers', 'CustomerController');

/*
|
| Front-End
|
*/
// Route::get('/', function () {
//     // return view('welcome');
//     return view('front.home');
// });



// Route::get('/', function () {
// 		return 'It work!';
// 	});



Route::get('objective', ['as'=>'objective.index', 'uses'=>'ProjectObjectiveController@index']);

Route::get('information', ['as'=>'information.index', 'uses'=>'ProjectInformationController@index']);

Route::get('productinformation', ['as'=>'productinformation.index', 'uses'=>'ProductInformationController@index']);

Route::get('productvalue', ['as'=>'productvalue.index', 'uses'=>'ProductValueController@index']);

Route::get('contactus', ['as'=>'contactus.index', 'uses'=>'ContactUsController@index']);

Route::get('payment', ['as'=>'payment.index', 'uses'=>'PaymentController@index']);

Route::get('logistic', ['as'=>'logistic.index', 'uses'=>'LogisticController@index']);

// Route::get('customer/register', 'CustomerController@register');
Route::get('customer/register', ['as'=>'customer.register', 'uses'=>'CustomerController@register']);

// Route::get('customers/{id}/edit', ['as'=>'customers.edit', 'uses'=>'CustomerController@edit']);

Route::get('member/forgotpassword', ['as'=>'member.forgotpassword', 'uses'=>'MemberController@forgotpassword']);
Route::post('member/sentemailforgotpassword', ['as'=>'member.sentemailforgotpassword', 'uses'=>'MemberController@sentemailforgotpassword']);
Route::resource('member', 'MemberController');

//add a route to that method separately, before you register the resource:
//For Basket
Route::get('basket/getBasket', ['as'=>'basket.getBasket', 'uses'=>'BasketController@getBasket']);
Route::get('basket/getexistbasket', ['as'=>'basket.getexistbasket', 'uses'=>'BasketController@getexistbasket']);
Route::get('basket/addBasket', ['as'=>'basket.addBasket', 'uses'=>'BasketController@addBasket']);
Route::get('basket/updateBasket', ['as'=>'basket.updateBasket', 'uses'=>'BasketController@updateBasket']);
Route::get('basket/addBasketByAdmin', ['as'=>'basket.addBasketByAdmin', 'uses'=>'BasketController@addBasketByAdmin']);
Route::get('basket/updateBasketQtyForCartPage', ['as'=>'basket.updateBasketQtyForCartPage', 'uses'=>'BasketController@updateBasketQtyForCartPage']);
Route::get('basket/updateBasketQtyForCartPageByAdmin', ['as'=>'basket.updateBasketQtyForCartPageByAdmin', 'uses'=>'BasketController@updateBasketQtyForCartPageByAdmin']);

Route::get('baskettype/{id}', ['as'=>'baskettype.showbaseontype', 'uses'=>'BasketController@showbaseontype']); 

Route::get('basket/removeProductFromBasket', ['as'=>'basket.removeProductFromBasket', 'uses'=>'BasketController@removeProductFromBasket']);
Route::get('basket/removeProductFromBasketByAdmin', ['as'=>'basket.removeProductFromBasketByAdmin', 'uses'=>'BasketController@removeProductFromBasketByAdmin']);

Route::get('basket/editCustomer', ['as'=>'basket.editCustomer', 'uses'=>'BasketController@editCustomer']);
Route::patch('basket/updateCustomer', ['as'=>'basket.updateCustomer', 'uses'=>'BasketController@updateCustomer']);
Route::patch('basket/updateCustomerMap', ['as'=>'basket.updateCustomerMap', 'uses'=>'BasketController@updateCustomerMap']);

//For card and checkout
Route::get('cart/{basketkey}', ['as'=>'basket.cart', 'uses'=>'BasketController@cart']);

Route::get('basket/checkout', ['as'=>'basket.checkout', 'uses'=>'BasketController@checkout']);

Route::get('basket/get_data_googlemap_api', ['as'=>'basket.get_data_googlemap_api', 'uses'=>'BasketController@get_data_googlemap_api']); 
Route::get('basket/googlemap_api', ['as'=>'basket.googlemap_api', 'uses'=>'BasketController@googlemap_api']); 


Route::get('basket/checkou', ['as'=>'basket.checkou', 'uses'=>'BasketController@checkou']); 

Route::post('basket/checkout_uploadfile', ['as'=>'basket.checkout_uploadfile', 'uses'=>'BasketController@checkout_uploadfile']); //

Route::post('basket/checkout_uploadfile_again', ['as'=>'basket.checkout_uploadfile_again', 'uses'=>'BasketController@checkout_uploadfile_again']);

Route::get('basket/checkout_getfile', ['as'=>'basket.checkout_getfile', 'uses'=>'BasketController@checkout_getfile']); 


Route::post('basket/checkout_buy', ['as'=>'basket.checkout_buy', 'uses'=>'BasketController@checkout_buy']); //status_checkout_buy
Route::get('basket/checkout_buyByAdmin',array('as'=>'basket.checkout_buyByAdmin','uses'=>'BasketController@checkout_buyByAdmin'));

Route::get('basket/status_checkout_buy', ['as'=>'basket.status_checkout_buy', 'uses'=>'BasketController@status_checkout_buy']); //seemore_products

Route::get('seemore_products/{id}', ['as'=>'basket.seemore_products', 'uses'=>'BasketController@seemore_products']); 

Route::resource('basket', 'BasketController');




Route::get('gmenu_logoutin_d', ['as'=>'getview.gmenu_logoutin_d', 'uses'=>'GetviewController@gmenu_logoutin_d']);
Route::get('gmenu_logoutin_m', ['as'=>'getview.gmenu_logoutin_m', 'uses'=>'GetviewController@gmenu_logoutin_m']); 

Route::get('gmenu_historybuy_d', ['as'=>'getview.gmenu_historybuy_d', 'uses'=>'GetviewController@gmenu_historybuy_d']);
Route::get('gmenu_historybuy_m', ['as'=>'getview.gmenu_historybuy_m', 'uses'=>'GetviewController@gmenu_historybuy_m']);

// Route::get('gfooter_line1_d', ['as'=>'getview.gfooter_line1_d', 'uses'=>'GetviewController@gfooter_line1_d']);
// Route::get('gfooter_line1_m', ['as'=>'getview.gfooter_line1_m', 'uses'=>'GetviewController@gfooter_line1_m']);
Route::resource('getview', 'GetviewController');


// Route::get('member/login', ['as'=>'member.login', 'uses'=>'MemberController@index']); //Request $request
// Route::post('member/store', ['as'=>'member.store', 'uses'=>'MemberController@store']);

blog/resources/views/front/home.blade.php
@extends('layouts.front')



@section('content')


<!-- slider area -->
{{-- <div class="slider-area">
    <div class="slider">
        <div id="bg-slider" class="owl-carousel owl-theme">

            <div class="item"><img src="{{asset($fronthomes[1]->photo_path)}}" alt=""></div>
            <div class="item"><img src="{{asset($fronthomes[2]->photo_path)}}" alt=""></div>
            <div class="item"><img src="{{asset($fronthomes[3]->photo_path)}}" alt=""></div>

        </div>
    </div>
    <div class="slider-content">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-12">
                <h2>{{$fronthomes[0]->message}}</h2>
                <p></p>
            </div>
        </div>
    </div>
</div> --}}
  <div id="myCarousel" class="carousel slide" data-ride="carousel"">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img src="{{asset($fronthomes[1]->photo_path)}}" alt="">
        <div class="carousel-caption">
          {{-- <h1>{{$fronthomes[0]->message}}</h1> --}}
          {{-- <p>LA is always so much fun!</p> --}}
        </div>
      </div>

      <div class="item">
        <img src="{{asset($fronthomes[2]->photo_path)}}" alt="" >
        <div class="carousel-caption">
          {{-- <h1>{{$fronthomes[0]->message}}</h1> --}}
          {{-- <p>Thank you, Chicago!</p> --}}
        </div>
      </div>
    
      <div class="item">
        <img src="{{asset($fronthomes[3]->photo_path)}}" alt="">
        <div class="carousel-caption">
          {{-- <h1>{{$fronthomes[0]->message}}</h1> --}}
          {{-- <p>We love the Big Apple!</p> --}}
        </div>
      </div>
          <div class="carousel-caption">
          <h1>{{$fronthomes[0]->message}}</h1>
          {{-- <p>LA is always so much fun!</p> --}}
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<!-- End slider area -->


<!-- welcome area -->
<div class="content-area home-area-1 recent-property" style="background-color: #FCFCFC; padding-bottom: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 text-center page-title">
                <h2>{!! $fronthomes[4]->message !!}</h2>
                {!! $fronthomes[4]->message2 !!}
            </div>
        </div>
    </div>
</div>
<!-- End welcome area -->

<!-- producers area -->
<div class="content-area home-area-1 recent-property" style="background-color: #F3F3F3; padding-bottom: 0px;">
    <div class="container"> 
        <div class="row">
            <div class="col-md-12 col-sm-12 text-center page-title" style="padding-top: 0px;margin-bottom: 20px;">
                <h2>ข้อมูลข่าวสาร</h2>
            </div>
        </div>
        <div class="row">
            <div class="proerty-th">
               {{-- {!! $producers !!} --}}
                @foreach($producers as $producer)
                  <div class="col-md-4 ">
                    <div class="box-two proerty-item">
                      <div class="item-thumb">
                        <a href="{{ route('producer.show', $producer->id ) }}""><img src="{{asset($producer->photo_path)}}"></a>
                      </div>
                      <div class="item-entry overflow text-center">
                        {{$producer->title}}
                      </div>
                    </div>
                  </div>
                @endforeach

            </div>
        </div>


    </div>
</div>
<!-- End producers area -->


{{-- <hr> --}}
<!-- product area -->
<div class="content-area home-area-1 recent-property" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 text-center page-title" style="padding-top: 0px;margin-bottom: 20px;">
                <h2>สินค้ามาใหม่</h2>
            </div>
        </div>        



        <div class="row">
            <div class="proerty-th">

                @foreach($products as $product)
                    <div class="col-md-4 ">
                        <div class="box-two proerty-item">
                            <div class="item-thumb">
                                <a href="{{ route('basket.show', $product->id ) }}" ><img src="{{asset($product->photo_path)}}"></a>
                            </div>
                            <div class="item-entry overflow">
                                <h2 style="margin-top: 0px;margin-bottom: 0.5em;">
                                    <a href="{{ route('basket.show', $product->id ) }}">{{str_limit($product->name, 15)}}</a>
                                </h2>
                                <div style="width: 40%;float: right;">
                                    <input type="number" id="qty" class="form-control input-xs" placeholder="จำนวน" min="1" value="1" style="    margin-top: -40px;">
                                </div>
                                <div class="dot-hr"></div>
                                {{-- <span class="pull-left"><b>Area :</b> 120m </span> --}}
                                <span class="proerty-price pull-left">{{$product->prime}}฿<br><small>{{str_limit($product->detail, 25)}}</small></span>
                                {{-- Do not change space text in button id="basket" --}}
                                <button class="btn border-btn-green pull-right" id="basket" value="{{$product->id}}"><i></i><span class="sr-only">Loading...</span>หยิบใส่ตะกร้า</button>
                            </div>
                        </div>
                    </div>
                @endforeach

                <div class="col-md-12 text-center" style="margin-top: 20px;">
                    <div class="more-entry overflow">
                        {{-- <h5><a href="property-1.html" >CAN'T DECIDE ? </a></h5>
                        <h5 class="tree-sub-ttl">Show all properties</h5> --}}
                        <a class="btn border-btn more-black" href="{{route('basket.index')}}">สินค้าทั้งหมด</a>
                    </div>
                </div>
            </div>
        </div>




    </div>
</div>
<!-- End product area -->




@stop