blog/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as'=>'frontHome.index', 'uses'=>'FrontHomeController@index']);

Auth::routes();



Route::get('producer/showall',array('as'=>'producer.showall','uses'=>'ProducerController@showall'));

Route::get('producer/{id}',array('as'=>'producer.showa','uses'=>'ProducerController@showa'));

/*
|
| Back-End
|
*/
Route::group(['middleware'=>'auth'], function(){
	Route::resource('frontHome', 'FrontHomeController');

	Route::resource('objective', 'ProjectObjectiveController');

	Route::resource('information', 'ProjectInformationController');

	Route::resource('productinformation', 'ProductInformationController');

	Route::resource('productvalue', 'ProductValueController');

	Route::resource('contactus', 'ContactUsController');

	Route::resource('payment', 'PaymentController');

	Route::resource('logistic', 'LogisticController');

	Route::get('basket/edit_acc', ['as'=>'basket.edit_acc', 'uses'=>'BasketController@edit_acc']);
	Route::patch('basket/update_acc/{id}', ['as'=>'basket.update_acc', 'uses'=>'BasketController@update_acc']); //



	// Route::get('producer/createa',array('as'=>'producer.createa','uses'=>'ProducerController@createa'));

	Route::resource('producer', 'ProducerController');



	Route::get('reports/google',array('as'=>'reports.google','uses'=>'ReportsController@google'));
	Route::get('reports/bestsaler',array('as'=>'reports.bestsaler','uses'=>'ReportsController@bestsaler'));
	Route::resource('reports', 'ReportsController');
});


// Route::get('/home', 'HomeController@index')->name('home');

Route::get('home/checkout_buy',array('as'=>'home.checkout_buy','uses'=>'HomeController@checkout_buy'));

Route::get('home/seemore_products/{id}',array('as'=>'home.seemore_products','uses'=>'HomeController@seemore_products')); //update_status_basket

Route::get('home/update_status_basket/{id}',array('as'=>'home.update_status_basket','uses'=>'HomeController@update_status_basket')); //history

Route::get('home/update_cart_products/{id}',array('as'=>'home.update_cart_products','uses'=>'HomeController@update_cart_products'));

Route::get('/history',array('as'=>'home.history','uses'=>'HomeController@history'));

Route::get('/home', array('as'=>'home.index','uses'=>'HomeController@index'));


Route::get('deleteimg/{id}', ['as'=>'users.deleteimg', 'uses'=>'UserController@deleteimg']); 
Route::resource('users', 'UserController');

Route::resource('produceTypes', 'ProduceTypeController');

Route::resource('produces', 'ProduceController');

// Route::resource('provinces', 'ProvinceController');

// Route::resource('districts', 'DistrictController');

// Route::resource('subDistricts', 'SubDistrictController');

// Route::resource('zipcodes', 'ZipcodeController');



Route::get('customer/district/{id}',array('as'=>'create.ajax','uses'=>'AppBaseController@getDistrict'));

Route::get('customer/subdistrict/{id}',array('as'=>'create.ajax','uses'=>'AppBaseController@getSubDistrict'));

Route::get('customer/testFacebook','CustomerController@testFacebook');

Route::post('customer/testPost',array('as'=>'testPost','uses'=>'CustomerController@testPost'));

Route::get('customer/facebook',array('as'=>'customer/facebook', 'uses'=>'CustomerController@redirectToProvider'));
Route::get('customer/facebook/callback',array('as'=>'customer/facebook/callback ','uses'=>'CustomerController@handleProviderCallback'));

Route::get('customer/google',array('as'=>'customer/google', 'uses'=>'CustomerController@redirectToProviderGoogle'));
Route::get('customer/google/callback',array('as'=>'customer/google/callback','uses'=>'CustomerController@handleProviderCallbackGoogle'));

Route::post('customer/addRegister',array('as'=>'customer/addRegister','uses'=>'CustomerController@addRegister'));

Route::post('customer/addLitleRegister',array('as'=>'customer.addLitleRegister','uses'=>'CustomerController@addLitleRegister'));

//Route::resource('producer', 'ProducerController');
Route::resource('customers', 'CustomerController');

/*
|
| Front-End
|
*/
// Route::get('/', function () {
//     // return view('welcome');
//     return view('front.home');
// });



// Route::get('/', function () {
// 		return 'It work!';
// 	});



Route::get('objective', ['as'=>'objective.index', 'uses'=>'ProjectObjectiveController@index']);

Route::get('information', ['as'=>'information.index', 'uses'=>'ProjectInformationController@index']);

Route::get('productinformation', ['as'=>'productinformation.index', 'uses'=>'ProductInformationController@index']);

Route::get('productvalue', ['as'=>'productvalue.index', 'uses'=>'ProductValueController@index']);

Route::get('contactus', ['as'=>'contactus.index', 'uses'=>'ContactUsController@index']);

Route::get('payment', ['as'=>'payment.index', 'uses'=>'PaymentController@index']);

Route::get('logistic', ['as'=>'logistic.index', 'uses'=>'LogisticController@index']);

// Route::get('customer/register', 'CustomerController@register');
Route::get('customer/register', ['as'=>'customer.register', 'uses'=>'CustomerController@register']);

// Route::get('customers/{id}/edit', ['as'=>'customers.edit', 'uses'=>'CustomerController@edit']);

Route::get('member/forgotpassword', ['as'=>'member.forgotpassword', 'uses'=>'MemberController@forgotpassword']);
Route::post('member/sentemailforgotpassword', ['as'=>'member.sentemailforgotpassword', 'uses'=>'MemberController@sentemailforgotpassword']);
Route::resource('member', 'MemberController');

//add a route to that method separately, before you register the resource:
//For Basket
Route::get('basket/getBasket', ['as'=>'basket.getBasket', 'uses'=>'BasketController@getBasket']);
Route::get('basket/getexistbasket', ['as'=>'basket.getexistbasket', 'uses'=>'BasketController@getexistbasket']);
Route::get('basket/addBasket', ['as'=>'basket.addBasket', 'uses'=>'BasketController@addBasket']);
Route::get('basket/updateBasket', ['as'=>'basket.updateBasket', 'uses'=>'BasketController@updateBasket']);
Route::get('basket/addBasketByAdmin', ['as'=>'basket.addBasketByAdmin', 'uses'=>'BasketController@addBasketByAdmin']);
Route::get('basket/updateBasketQtyForCartPage', ['as'=>'basket.updateBasketQtyForCartPage', 'uses'=>'BasketController@updateBasketQtyForCartPage']);
Route::get('basket/updateBasketQtyForCartPageByAdmin', ['as'=>'basket.updateBasketQtyForCartPageByAdmin', 'uses'=>'BasketController@updateBasketQtyForCartPageByAdmin']);

Route::get('baskettype/{id}', ['as'=>'baskettype.showbaseontype', 'uses'=>'BasketController@showbaseontype']); 

Route::get('basket/removeProductFromBasket', ['as'=>'basket.removeProductFromBasket', 'uses'=>'BasketController@removeProductFromBasket']);
Route::get('basket/removeProductFromBasketByAdmin', ['as'=>'basket.removeProductFromBasketByAdmin', 'uses'=>'BasketController@removeProductFromBasketByAdmin']);

Route::get('basket/editCustomer', ['as'=>'basket.editCustomer', 'uses'=>'BasketController@editCustomer']);
Route::patch('basket/updateCustomer', ['as'=>'basket.updateCustomer', 'uses'=>'BasketController@updateCustomer']);
Route::patch('basket/updateCustomerMap', ['as'=>'basket.updateCustomerMap', 'uses'=>'BasketController@updateCustomerMap']);

//For card and checkout
Route::get('cart/{basketkey}', ['as'=>'basket.cart', 'uses'=>'BasketController@cart']);

Route::get('basket/checkout', ['as'=>'basket.checkout', 'uses'=>'BasketController@checkout']);

Route::get('basket/get_data_googlemap_api', ['as'=>'basket.get_data_googlemap_api', 'uses'=>'BasketController@get_data_googlemap_api']); 
Route::get('basket/googlemap_api', ['as'=>'basket.googlemap_api', 'uses'=>'BasketController@googlemap_api']); 


Route::get('basket/checkou', ['as'=>'basket.checkou', 'uses'=>'BasketController@checkou']); 

Route::post('basket/checkout_uploadfile', ['as'=>'basket.checkout_uploadfile', 'uses'=>'BasketController@checkout_uploadfile']); //

Route::post('basket/checkout_uploadfile_again', ['as'=>'basket.checkout_uploadfile_again', 'uses'=>'BasketController@checkout_uploadfile_again']);

Route::get('basket/checkout_getfile', ['as'=>'basket.checkout_getfile', 'uses'=>'BasketController@checkout_getfile']); 


Route::post('basket/checkout_buy', ['as'=>'basket.checkout_buy', 'uses'=>'BasketController@checkout_buy']); //status_checkout_buy
Route::get('basket/checkout_buyByAdmin',array('as'=>'basket.checkout_buyByAdmin','uses'=>'BasketController@checkout_buyByAdmin'));

Route::get('basket/status_checkout_buy', ['as'=>'basket.status_checkout_buy', 'uses'=>'BasketController@status_checkout_buy']); //seemore_products

Route::get('seemore_products/{id}', ['as'=>'basket.seemore_products', 'uses'=>'BasketController@seemore_products']); 

Route::resource('basket', 'BasketController');




Route::get('gmenu_logoutin_d', ['as'=>'getview.gmenu_logoutin_d', 'uses'=>'GetviewController@gmenu_logoutin_d']);
Route::get('gmenu_logoutin_m', ['as'=>'getview.gmenu_logoutin_m', 'uses'=>'GetviewController@gmenu_logoutin_m']); 

Route::get('gmenu_historybuy_d', ['as'=>'getview.gmenu_historybuy_d', 'uses'=>'GetviewController@gmenu_historybuy_d']);
Route::get('gmenu_historybuy_m', ['as'=>'getview.gmenu_historybuy_m', 'uses'=>'GetviewController@gmenu_historybuy_m']);

// Route::get('gfooter_line1_d', ['as'=>'getview.gfooter_line1_d', 'uses'=>'GetviewController@gfooter_line1_d']);
// Route::get('gfooter_line1_m', ['as'=>'getview.gfooter_line1_m', 'uses'=>'GetviewController@gfooter_line1_m']);
Route::resource('getview', 'GetviewController');


// Route::get('member/login', ['as'=>'member.login', 'uses'=>'MemberController@index']); //Request $request
// Route::post('member/store', ['as'=>'member.store', 'uses'=>'MemberController@store']);

blog/resources/views/history.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            ประวัติคำสั่งซื้อ
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-header">
                <h1 class="text-center">ประวัติคำสั่งซื้อ</h1>
            </div>
            <div class="box-body">
               @if(Session::has('home_meassage'))
                <div class="alert alert-success" role="alert">
                    {{Session::get('home_meassage')}}
                </div>
               @endif

	          <div class="table-responsive" style="margin-top: 20px;">          
		          <table class="table table-hover">
		            <thead>
		              <tr>
		                <th class="col-md-2 text-center">รหัสอ้างอิงการสั่งซื้อ</th>
		                <th class="col-md-2 text-center">ลูกค้า</th>
		                <th class="col-md-2 text-center">หลักฐานการโอนเงิน</th>
		                <th>รูปแบบการจ่ายเงิน </th>
		                <th>สถานที่นัดรับ</th>
		                <th>สั่งซื้อเมื่อ</th>
		                <th class="col-md-1 text-center">ดูสินค้า</th>
		                {{-- <th>จ่ายสินค้า</th> --}}
		              </tr>
		            </thead>
		            <tbody>
		             
		              @foreach($baskets_buying as $basket_buying)
		                <tr>
		                    <td  class="col-md-2 text-center">
		                      {{$basket_buying->basket_key}}
		                      {{-- {{$basket_buying->basket_id}} --}}
		                    </td>
		                    <td class="col-md-2 text-center">
		                    	<a title="ดูข้อมูลลูกค้า" href="{{route('customers.show', [$basket_buying->customer_id])}}">{{$basket_buying->first_name}} {{$basket_buying->last_name}}</a>
		                    </td>
		                    <td class="col-md-2 text-center">
		                      {{-- <img id="expand_image" src="{{asset($basket_buying->photo_path)}}" class="img-thumbnail" style="width: 50%;"> --}}

                  			@if($basket_buying->photo_path)
		                        <a href="{{asset($basket_buying->photo_path)}}" target="_blank">เปิดดู</a>
		                      @else
		                     	 <a href="#" >ไม่มีการอัพโหลด</a>
		                      @endif		                      
		                    </td>
		                    <td>
		                    	{{$basket_buying->pay}}
		                    </td>
		                    <td class="">
		                      {{$basket_buying->receive_place}}
		                    </td>
		                    <td class="">
		                      {{$basket_buying->updated_at_basket}}
		                    </td>
		                    <td class="col-md-1 text-center">
		                      <a href="{{route('home.seemore_products', $basket_buying->basket_key)}}" class="btn btn-info">เรียกดูสินค้า</a>
		                    </td>
		                  {{--   <td>
		                    	 <a href="{{route('home.update_status_basket', $basket_buying->basket_key)}}" class="btn btn-success">จ่ายสินค้า</a>
		                    </td> --}}
		                </tr>


		              @endforeach

		            </tbody>
		          </table>
	          </div>


            </div>
            <div class="box-footer text-right">
                {{ $baskets_buying->links() }}
            </div>
        </div>
    </div>
@endsection

blog/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            คำสั่งซื้อ
        </h1>
    </section>
    <div class="content">
    	@include('flash::message')
        <div class="box box-primary">
            <div class="box-header">
                <h1 class="text-center">คำสั่งซื้อ</h1>
            </div>
            <div class="box-body">
               @if(Session::has('home_meassage'))
                <div class="alert alert-success" role="alert">
                    {{Session::get('home_meassage')}}
                </div>
               @endif

	          <div class="table-responsive" style="margin-top: 20px;">          
		          <table class="table table-hover">
		            <thead>
		              <tr>
		                <th class="col-md-1 text-center">รหัสอ้างอิงการสั่งซื้อ</th>
		                <th class="col-md-2 text-center">ลูกค้า</th>
		                <th class="col-md-2 text-center">หลักฐานการโอนเงิน</th>
		                <th>รูปแบบการจ่ายเงิน </th>
		                <th>สถานที่นัดรับ</th>
		                <th>สั่งซื้อเมื่อ</th>
		                <th class="col-md-1 text-center">ดูสินค้า</th>
		                <th class="col-md-1 text-center">ปรับเปลี่ยนคำสั่งซื้อ</th>
		                <th>จ่ายสินค้า</th>
		              </tr>
		            </thead>
		            <tbody>
		             
		              @foreach($baskets_buying as $basket_buying)
		                <tr>
		                    <td  class="col-md-1 text-center">
		                      {{$basket_buying->basket_key}}
		                      {{-- {{$basket_buying->basket_id}} --}}
		                    </td>
		                    <td class="col-md-2 text-center">
		                    	<a title="ดูข้อมูลลูกค้า" href="{{route('customers.show', [$basket_buying->customer_id])}}">{{$basket_buying->first_name}} {{$basket_buying->last_name}}</a>
		                    </td>
		                    <td class="col-md-2 text-center">

		                      {{-- <img id="expand_image" src="{{asset($basket_buying->photo_path)}}" class="img-thumbnail" style="width: 50%;"> --}}
		                      {{-- @if(strpos($basket_buying->photo_path, '.pdf') !== false) --}}
		                      @if($basket_buying->photo_path)
		                        <a href="{{asset($basket_buying->photo_path)}}" target="_blank">เปิดดู</a>
		                  {{--     @else

		                        <img id="expand_imagea" src="{{asset($basket_buying->photo_path)}}" class="img-thumbnail" style="width: 50%;">
	
		                      @endif --}}
		                      @else
		                     	 <a href="#" >ยังไม่มีการอัพโหลด</a>
		                      @endif
		                    </td>
		                    <td>
		                    	{{$basket_buying->pay}}
		                    </td>
		                    <td class="">
		                    	@if($basket_buying->receive_place!='จัดส่งตามแผนที่')
		                      		{{$basket_buying->receive_place}}
		                      	@else
		                      		<?php
		                      			$d_ = json_decode($basket_buying->lat_long, true);
		                      			// echo "$d_";
		                      		?>
		                      		<a target="_blank" href="http://maps.google.com/?q={{$d_['lat']}},{{$d_['long']}}">คลิ๊กดูแผนที</a>
		                      		<hr>
		                      		<u>ข้อมูลเพิ่มเติม:</u> {{$d_['data_more']}}
		                      	@endif
		                    </td>
		                    <td class="">
		                      {{$basket_buying->basket_updated_at}}
		                    </td>
		                    <td class="col-md-1 text-center">
		                      <a href="{{route('home.seemore_products', $basket_buying->basket_key)}}" class="btn btn-info">เรียกดูสินค้า</a>
		                    </td>
		                    <td class="col-md-1 text-center">
		                    	<a href="{{route('home.update_cart_products', $basket_buying->basket_key)}}" class="btn btn-primary">ปรับเปลี่ยน</a>
		                    </td>
		                    <td>
		                    	 <a href="{{route('home.update_status_basket', $basket_buying->basket_key)}}" class="btn btn-success">จ่ายสินค้า</a>
		                    </td>
		                </tr>


		              @endforeach

		            </tbody>
		          </table>
	          </div>


            </div>
            <div class="box-footer text-right">
                {{ $baskets_buying->links() }}
            </div>
        </div>
    </div>
@endsection

blog/resources/views/seemore_products.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            รายละเอียดคำสั่งซื้อ
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-header">
                <h2 class="page-title">รายละเอียดสินค้า ของรหัสอ้างอิงคำสั่งซื้อ: {{$products[0]->basket_key}}</h2>
                <h3>นัดรับที่: {{$products[0]->receive_place}}</h3>    
            </div>
            <div class="box-body">

        <div class="row">
          <div class="table-responsive" style="margin-top: 20px;">          
          <table class="table table-hover">
            <thead>
              <tr>
                {{-- <th class="col-md-1 text-center">ลบ</th> --}}
                <th>รูปภาพ</th>
                <th>ชื่อสินค้า</th>
                <th>ราคา</th>
                <th>จำนวน</th>
                <th>ราคารวม</th>
              </tr>
            </thead>
            <tbody>

              <?php $sum_total_price = 0;?>
              @foreach($products as $product)
                <tr>
{{--                   <td class="col-md-1 text-center">
                    <a id="remove-cart" style="cursor: pointer; color: red;" title="นำ {{$product->name}} ออกจากตะกร้าสินค้า" onclick="removeProductFromBasket({{$product->id}}, 1);">
                      <i id="remove-cart-symbol" class="fa fa-minus-square-o fa-2x" style="margin-top: 15px;" aria-hidden="true"></i>
                    </a>
                  </td> --}}
                  <td class="col-md-1">
                    <a style="cursor: pointer;" title="ดูรายละเอียดของ {{$product->name}}"><img src="{{asset($product->photo_path)}}" style="width: 100%;"></a>  
                  </td>
                  <td style="color: #5cb85c;">
                    <a style="cursor: pointer;" title="ดูรายละเอียดของ {{$product->name}}">
                      {{$product->name}}
                    </a>
                  </td>
                  <td>
                    <span id="cart-price">{{$product->prime}}</span>฿
                  </td>
                  <td class="col-md-2">
                    <input type="hidden" id="hidden-product-id" value="{{$product->id}}">
                    {{$product->qty}}
                    {{-- <input type="number" id="cart-qty" class="form-control" placeholder="จำนวน" min="1" value="{{$product->qty}}"> --}}
                  </td>
                  <td>
                    <label id="cart-total-qty">
                      <?php 
                        $total_price = 0;
                        $total_price = $product->qty * $product->prime; 

                        $sum_total_price += $total_price;
                      ?>
                      {{number_format($total_price,2)}}
                    </label>฿
                  </td>
                </tr>
              @endforeach

            </tbody>
          </table>
          </div>
        </div>



       {{--  <br> --}}
        <div class="row" style="margin-top: -20px">
            <div class="col-md-4">
                
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
                {{-- <a onclick="updateCart(this);" class="btn border-btn-green" style="padding: 15px; width: 100%">ปรับปรุงตะกร้าสินค้า</a> --}}
                <div style="margin-bottom: 10px;"></div>
                {{-- (กรณีที่เปลี่ยนจำนวน แล้วราคารวมไม่เปลี่ยนแปลง ให้กดอัพเดท) --}}
                <div class="thumbnail">
                  <h4>ราคารวมทั้งหมด:  <span id="sum-total-price">{{$sum_total_price}}</span>฿</h4>
                </div>
                <a href="{{ url()->previous() }}" class="btn btn-success pull-right" style="padding: 15px; width: 100%"><i class="fa fa-arrow-left" aria-hidden="true"></i> กลับ</a>
            </div>    
        </div>

            </div>
            <div class="box-footer">
                
            </div>
        </div>
    </div>
@endsection

blog/resources/views/update_cart_products.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            ปรับเปลี่ยนคำสั่งซื้อสินค้า
        </h1>
    </section>
    <div class="content">
      @include('flash::message')
        <div class="box box-primary">
            <div class="box-header">
                <h2 class="page-title">รหัสอ้างอิงคำสั่งซื้อ: {{$products[0]->basket_key}}</h2>
                <h3>นัดรับที่: {{$products[0]->receive_place}}</h3>    
            </div>
            <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                  <form method="get" action="{{route('basket.addBasketByAdmin')}}">
                    <div class="input-group">
                      <input type="hidden" name="basketKey" value="{{$products[0]->basket_key}}">
                     {!! Form::select('productID', ['0'=>'---เลือกสินค้าที่ต้องการ---'] + $Produce, null, ['class' => 'form-control select2','id'=>'productID']) !!}
                      <span class="input-group-btn">
                        <button class="btn btn-primary btn-xl" type="submit">เพิ่มสินค้าเข้าคำสั่งซื้อ</button>
                      </span>
                    </div> {{-- /input-group --}}
                  </form>
                </div>
            </div>
        <div class="row">
          <div class="table-responsive" style="margin-top: 20px;">          
          <table class="table table-hover">
            <thead>
              <tr>
                {{-- <th class="col-md-1 text-center">ลบ</th> --}}
                <th>รูปภาพ</th>
                <th>ชื่อสินค้า</th>
                <th>ราคา</th>
                <th>จำนวน</th>
                <th>ราคารวม</th>
                <th class="col-md-1 text-center">ลบ</th>
              </tr>
            </thead>
            <tbody>

              <?php $sum_total_price = 0;?>
              @foreach($products as $product)
                <tr>
{{--                   <td class="col-md-1 text-center">
                    <a id="remove-cart" style="cursor: pointer; color: red;" title="นำ {{$product->name}} ออกจากตะกร้าสินค้า" onclick="removeProductFromBasket({{$product->id}}, 1);">
                      <i id="remove-cart-symbol" class="fa fa-minus-square-o fa-2x" style="margin-top: 15px;" aria-hidden="true"></i>
                    </a>
                  </td> --}}
                  <td class="col-md-1">
                    <a style="cursor: pointer;" title="ดูรายละเอียดของ {{$product->name}}"><img src="{{asset($product->photo_path)}}" style="width: 100%;"></a>  
                  </td>
                  <td style="color: #5cb85c;">
                    <a style="cursor: pointer;" title="ดูรายละเอียดของ {{$product->name}}">
                      {{$product->name}}
                    </a>
                  </td>
                  <td>
                    <span id="cart-price">{{$product->prime}}</span>฿
                  </td>
                  <td class="col-md-2">
                    <form method="get" action="{{route('basket.updateBasketQtyForCartPageByAdmin')}}">
                      <div class="input-group">
                        <input type="hidden" name="productID" value="{{$product->id}}">
                        <input type="hidden" name="basketKey" value="{{$products[0]->basket_key}}">
                        <input type="number" name="qty" class="form-control" placeholder="จำนวน" min="1" value="{{$product->qty}}">
                        <span class="input-group-btn">
                          <button class="btn btn-primary" type="submit">ปรับปรุง</button>
                        </span>
                      </div>
                    </form>
                  </td>
                  <td>
                    <label id="cart-total-qty">
                      <?php 
                        $total_price = 0;
                        $total_price = $product->qty * $product->prime; 

                        $sum_total_price += $total_price;
                      ?>
                      {{number_format($total_price,2)}}
                    </label>฿
                  </td>
                  <td class="col-md-1 text-center">
 {{--                    <a id="remove-cart" style="cursor: pointer; color: red;" title="นำ {{$product->name}} ออกจากตะกร้าสินค้า" onclick="removeProductFromBasket({{$product->id}}, 1);">
                      <i id="remove-cart-symbol" class="fa fa-minus-square-o fa-2x" style="margin-top: 15px;" aria-hidden="true"></i>
                    </a> --}}
                    <form method="get" action="{{route('basket.removeProductFromBasketByAdmin')}}">
                      <input type="hidden" name="basketKey" value="{{$products[0]->basket_key}}">
                      <input type="hidden" name="productID" value="{{$product->id}}">
                      <button type="submit" class="btn btn-danger" title="นำ {{$product->name}} ออกจากคำสั่งซื้อ">
                        <i id="remove-cart-symbol" class="fa fa-minus-square-o"" aria-hidden="true"></i>
                      </button>
                      {{-- <a style="cursor: pointer; color: red;" type="submit" title="นำ {{$product->name}} ออกจากตะกร้าสินค้า">
                        <i id="remove-cart-symbol" class="fa fa-minus-square-o fa-2x" style="margin-top: 15px;" aria-hidden="true"></i>
                      </a> --}}
                    </form>


                  </td>
                </tr>
              @endforeach

            </tbody>
          </table>
          </div>
        </div>



       {{--  <br> --}}
        <div class="row" style="margin-top: -20px">
            <div class="col-md-4">
                
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
                {{-- <a onclick="updateCart(this);" class="btn border-btn-green" style="padding: 15px; width: 100%">ปรับปรุงตะกร้าสินค้า</a> --}}
                <div style="margin-bottom: 10px;"></div>
                {{-- (กรณีที่เปลี่ยนจำนวน แล้วราคารวมไม่เปลี่ยนแปลง ให้กดอัพเดท) --}}
                <div class="thumbnail">
                  <h4>ราคารวมทั้งหมด:  <span id="sum-total-price">{{$sum_total_price}}</span>฿</h4>
                </div>

               {{--  <a href="{{ route('home.index') }}" class="btn btn-success pull-right" style="padding: 15px; width: 100%"><i class="fa fa-arrow-left" aria-hidden="true"></i> กลับและ <i class="fa fa-envelope" aria-hidden="true"></i> ส่งอีเมลแจ้งลูกค้า</a> --}}
                <form method="get" action="{{route('basket.checkout_buyByAdmin')}}">
                    <input type="hidden" name="basketKey" value="{{$products[0]->basket_key}}">
                    <button type="submit" class="btn btn-success pull-right" style="padding: 15px; width: 100%"><i class="fa fa-arrow-left" aria-hidden="true"></i> กลับและ <i class="fa fa-envelope" aria-hidden="true"></i> ส่งอีเมลแจ้งลูกค้า</button>
                </form>
            </div>    
        </div>

            </div>
            <div class="box-footer">
                
            </div>
        </div>
    </div>
@endsection